### ISSUE TITLE
Update to Latest Tachyons Version

### ISSUE THREAD

**Issue by triallax** [justgage/tachyons-elm#23]
The latest Tachyons version currently supported by this library is 4.8.1.
I would appreciate if it was upgraded to Tachyons 4.10.0.
Thanks in advance.

**Comment by justgage** [comment]
Turns out the code was right but I forgot to update the documentation in a few places. Published a new version. 4.1.2

**Comment by justgage** [comment]
New commit: https://github.com/justgage/tachyons-elm/commit/31cb915c6f0db75735bfa902702f356f25e76c27

**Comment by triallax** [comment]
I think you made a mistake in the commit. You updated the version from Tachyons 4.8.1 to 4.11.2 but the latest version that I was able to download is 4.11.1.

**Comment by justgage** [comment]
Right you are, I'll fix it

**Comment by justgage** [comment]
Published as 4.1.3: https://package.elm-lang.org/packages/justgage/tachyons-elm/latest/Tachyons#tachyons

**Comment by justgage** [comment]
Tell me if this fixes your issue @MohammedSheikhIbrahim 😬

**Comment by triallax** [comment]
Yes it does, thanks for your efforts @justgage!

**Comment by justgage** [comment]
No problem! Sorry I don't use this on a daily basis so I don't notice the issues with it nearly as often.
