### ISSUE TITLE
CONTRIBUTING.md

### ISSUE THREAD

**Issue by MartinKavik** [justgage/tachyons-elm#5]
[github.com/blog/1184-contributing-guidelines](https://github.com/blog/1184-contributing-guidelines)
It could be useful for new contributors.

My setup:

- Windows 10
- [Visual Studio Code](https://code.visualstudio.com/)
  - extension [Prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode)
  - `settings.json` - **`"editor.formatOnSave": true`**
- [Git for Windows](https://git-for-windows.github.io/)
  - contains **bash** for running **`build.sh`**

**Comment by justgage** [comment]
Fixed with #13
