### ISSUE TITLE
Think about more type safe version?

### ISSUE THREAD

**Issue by justgage** [justgage/tachyons-elm#8]
Not exactly sure what this would look like but perhaps this would be nice? The Bootstrap package might be a good reference. Discussion welcome.

**Comment by MartinKavik** [comment]
Do you want to add some type checkers (e.g. https://flow.org/) or change language (e.g. Typescript)? And why?
P.S. Could you post a link to *Bootstrap package* from your comment?

**Comment by justgage** [comment]
Maybe. However I'm more worried about the Elm side. The main thing I was thinking about was this: http://package.elm-lang.org/packages/rundis/elm-bootstrap/latest. However looking at it briefly it may not be the best fit. It seems they have a concept of components which doesn't make a lot of sense with Tachyons. So perhaps this isn't a great fit 🤷‍♂️

**Comment by MartinKavik** [comment]
@justgage We can try to invent some "components concept" suitable for Elm and Tachyons. I've created new repo for experiments - https://github.com/MartinKavik/tachyons-elm-partials and added you as a collaborator - feel free to change everything you want.

**Comment by justgage** [comment]
Interesting, I'll take a look. I'm starting to think that perhaps just elm-html templates of components. Maybe using something like: https://mbylstra.github.io/html-to-elm/ and https//tachyons.io/components/ . It seems in the spirit of Tachyons to only give people starting templates rather than built out views.
